import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'flutter_builder_generator.dart';

Builder nativeCallBuilder(BuilderOptions options) => LibraryBuilder(
      ParamGenerator(options: options),
      generatedExtension: ".test.g.dart",
      // header: 'Generated by ParamGenerator, do not edit.',
    );
